version: '3.9'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: amil-zakat-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    networks:
      - tunnel-network

networks:
  tunnel-network:
    external: true
