import { test, expect } from '@playwright/test';

test.describe('Admin Panel', () => {
  test('redirects to home if not admin', async ({ page }) => {
    await page.goto('/admin');
    // If pending is not properly awaited, it might redirect to / or it might stay if not implemented well
    // But anyway, it should end up at /
    await expect(page).toHaveURL('/');
  });

  test('allows mock admin login and creates a campaign', async ({ page }) => {
    // Go to account page
    await page.goto('/akun');
    
    // Click the mock login button
    await Promise.all([
      page.waitForNavigation(),
      page.click('text=Mock Login (Admin)')
    ]);

    // The endpoint redirects to / after setting the cookie
    await expect(page).toHaveURL('/');

    // Now go to admin dashboard
    await page.goto('/admin');
    await expect(page.locator('text=Admin Dashboard')).toBeVisible();

    // Go to create campaign
    await page.click('text=Buat Campaign Baru');
    await expect(page).toHaveURL('/admin/campaigns/create');

    // Fill form
    const uniqueTitle = `Test Campaign ${Date.now()}`;
    await page.fill('input[placeholder="Masukkan judul"]', uniqueTitle);
    await page.fill('textarea[placeholder="Ceritakan detail program"]', 'This is a test description generated by automated tests.');
    await page.fill('input[placeholder="0"]', '1000000');
    
    // Submit
    await page.click('text=Simpan Campaign');

    // Should redirect to campaigns list and show toast
    await expect(page).toHaveURL('/admin/campaigns');
    await expect(page.locator('text=Campaign berhasil dibuat')).toBeVisible();

    // The new campaign should be in the list
    await expect(page.locator(`text=${uniqueTitle}`)).toBeVisible();
  });
});
